frontend: default
frontend_conf:
  n_fft: 512
  win_length: 512
  hop_length: 128
  window: hann
  n_mels: 80
  fmin: 80
  fmax: 7600

specaug: specaug
specaug_conf:
  apply_time_warp: false
  time_mask_width_range: [0, 40]
  freq_mask_width_range: [0, 20]
  num_time_mask: 2
  num_freq_mask: 2

normalize: null
# normalize_conf: {}

encoder: mamba
encoder_conf:
  output_size: 256
  hidden_size: 512
  num_blocks: 12

  mamba_type: mamba1

  d_state: 16
  d_conv: 4
  expand: 2

  conv_kernel_size: 15
  conv_num_layers: 2

  linear_units: 2048

  dropout_rate: 0.10

  chunk_size: 0

decoder: rnn
decoder_conf:
  rnn_type: lstm
  num_layers: 2
  hidden_size: 512
  dropout: 0.10
  sampling_probability: 0.0

ctc_conf:
  dropout_rate: 0.1

model_conf:
  ctc_weight: 0.3
  lsm_weight: 0.0
  length_normalized_loss: false

optim: adamw
optim_conf:
  lr: 3.0e-4
  weight_decay: 1.0e-4
  betas: [0.9, 0.98]
  eps: 1.0e-8

scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000

max_epoch: 5

resume: true

batch_type: numel
batch_bins: 2500000

accum_grad: 2

grad_clip: 5.0

num_workers: 8